import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import api from '../utils/api';
import { useDispatch } from 'react-redux';
import { addToCart } from '../redux/cartSlice';
import { toast } from 'react-toastify';

const MealPlanner = () => {
    const [plan, setPlan] = useState([]);
    const [loading, setLoading] = useState(true);
    const [message, setMessage] = useState('');
    const dispatch = useDispatch();

    useEffect(() => {
        const fetchPlan = async () => {
            try {
                const { data } = await api.get('/recommendations/meal-plan');
                if (data.success) {
                    setPlan(data.plan || []);
                    setMessage(data.message || '');
                }
            } catch (_) { }
            finally { setLoading(false); }
        };
        fetchPlan();
    }, []);

    const handleAddToCart = (item) => {
        if (!item) return;
        dispatch(addToCart({ ...item, quantity: 1, shopId: item.shop?._id || item.shop }));
        toast.success(`Added ${item.name} to cart!`);
    };

    if (loading) return (
        <div className="p-8 text-center text-gray-400">
            <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin mx-auto mb-3" />
            Creating your personalized meal plan...
        </div>
    );

    if (plan.length === 0) return (
        <div className="p-8 text-center">
            <p className="text-4xl mb-3">🥗</p>
            <p className="font-black text-gray-700 dark:text-gray-300 text-lg">Not Enough Data</p>
            <p className="text-sm text-gray-400 mt-1">{message || 'Order more frequently to unlock your personalized 7-day meal plan!'}</p>
        </div>
    );

    return (
        <div className="p-6">
            <div className="mb-6">
                <h2 className="text-xl font-black text-gray-900 dark:text-white">🧠 AI Meal Planner</h2>
                <p className="text-xs text-gray-400 font-medium mt-1">Based on your recent cravings and order history</p>
            </div>

            <div className="space-y-4">
                {plan.map((day, i) => (
                    <motion.div
                        key={i}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.1 }}
                        className="bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 rounded-3xl p-4 flex items-center gap-4 shadow-sm"
                    >
                        <div className="w-16 h-16 flex-shrink-0 bg-gray-100 dark:bg-gray-700 rounded-2xl overflow-hidden">
                            <img src={day.suggestion?.image || 'https://via.placeholder.com/150'} className="w-full h-full object-cover" alt="" />
                        </div>
                        <div className="flex-1">
                            <div className="flex justify-between items-start">
                                <div>
                                    <p className="text-[10px] font-black text-primary uppercase tracking-widest">{day.day} · {day.type}</p>
                                    <h3 className="font-black text-gray-900 dark:text-white text-sm truncate w-40">{day.suggestion?.name}</h3>
                                    <p className="text-[10px] text-gray-400 font-bold">{day.suggestion?.shop?.name}</p>
                                </div>
                                <button
                                    onClick={() => handleAddToCart(day.suggestion)}
                                    className="bg-gray-100 dark:bg-gray-700 hover:bg-primary hover:text-white text-gray-600 dark:text-gray-300 w-8 h-8 rounded-full flex items-center justify-center transition-colors"
                                >
                                    +
                                </button>
                            </div>
                        </div>
                    </motion.div>
                ))}
            </div>

            <p className="mt-6 text-[10px] text-gray-400 text-center font-medium px-4">
                * This plan is generated by analyzing your favorite cuisines and ordering patterns.
                Suggestions may vary based on restaurant availability.
            </p>
        </div>
    );
};

export default MealPlanner;
